language: node_js
node_js:
- '7'
branches:
  only:
  - master
before_script: 
addons:
  apt:
    packages:
    - sshpass
before_install:
  - openssl aes-256-cbc -K $encrypted_abf1c25cba00_key -iv $encrypted_abf1c25cba00_iv
    -in travis-pri.enc -out travis-pri -d
  - bash .script/install.sh
script:
  - bash .script/build.sh
  - bash .script/test.sh
after_success:
  - bash .script/deploy.sh
notifications:
  email:
    on_failure: change
    on_success: change