language: node_js
node_js:
- '7'
branches:
  only:
  - master
before_script: 
addons:
  apt:
    packages:
    - sshpass
script:
- ng build --prod
after_success:
- ls -l
- tar -czf package.tgz dist
- ls -l
- export SSHPASS=$DEPLOY_PASS
- sshpass -e scp -o stricthostkeychecking=no package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
- sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh
notifications:
  email:
    on_failure: change
    on_success: change
env:
  global:
  - secure: dIDKWKxM170t4MWJInL04+j+vJl9wKtb6p/m5ev90+RPRRXXaFmWd333jYptMjYX/4b0/L60x0FBB6DbSZnUx0b0EoV7IRuZogQxlwLxiO6p6OKHc9ujjhYTeTw+bz0WdEGyag9Kw4ZqdWCefxg9DrlFgK2bjIqtkP5Cj8lJsHSEvxglAXKWM0eeGdSa0b7NYALUj6VQKhT995HgXm02QB6I+Yh3jFRrDLQFEaw2hCuLy7nNlXFeXtqzfwESyPZ21ZmydQRuHSoWTTE5d8KY6YlUsB/1sm129GUwxT9jswN969kOIVhHcbMBFUIgAZMPnKTyIdOY93lH4b/CcD0PAKQuTlakKrtpS6b57/RBlpMFx+QGYyKxczkVNkJvkdEkLCk/KEcxnzAvN/tCCEBLvxrr/TEELvQmsID8ExJFV7J9QJWHG6MKQW3VD8fPKk5GuPkXheAmsDC8gn/W7yr1+32ea8FIE5/Lcp6iSv9H7gjtTiWOFLh1zooeuQkPBxYgEZrqarlOcboaJuPbrWDfd/rVfMYQfkrkAW+LWgW+bw3s/p6lQJMkVP/8vw5dQLqwr32EvUSlLxk8JnePaDV0pkb+kyp9UVgfzn4Cm2f0y5isLVJvylAPQiLao3f9LmVxM8cPXRi7pDh+H7nn1abNB/78dPA/ChNyknaI+aN/5q8=
  - secure: hMvtI18FMi0VSlJ1hUu2fmxdoQqcVg0FFcoxU7YGpnvSYfqs5g8puK2gSYA7wov5KJbLFaY1rSAkxk9KOZVnmyWlsV8/e9odMzez+U0CRPA/kH03ig1WLjC+z9w7r1WvG2EgocTAZ4OgB/BkrbTUOBvDJZDDDAnMEq/F0NnNhkaFJw+j5BVqJikhMYCF0upOEglbI+oOyz7c+dAXkXkryMvKKPWirmbX9fqcM8JOkNnZVKjd8B86CNvwPRBUl9AvOMmk6YSs1OvashbYZTjfZ2ovaZKNcL4rIIpkZfXWoZ1rz7swJMSLFBRUcLuR0Tvqo+zdr9bKiAeObwEGhuekp13S80kXdphJWdlJh/pKs13K0rdFZQuaf3M7nTukGALfRowVFzTK5mjH5y4GvbLho1oHSvOZu46j8E9ahl1wcvrCaCgzIzRljdQ7bD8//NZeb/n1BjK66t0q8hFUZgRtK1pnwxjmpCfPrVPDqU3ew5ROeh9A8hpl97AuFEJ+2actsXu9qV6NB0+JdXrbTA984ToPx99hxyH7vLpDUA+HMWatCTLw6R9pg+3Dp4x1FhITQLoO+5+GjsHsUaS2hk4vcOimSS4YHXEHsfuDp4pBa5fE8mY0pAQyEedXxq2WLHAn/Tfnkxm3vqNAssptVM7J6tZ5/nOedq5w/Za8jVEOSTg=
  - secure: bLhTIc+c9Q865UR6zKp09iLAQnlgp9Q6QoCu/yKMXpKjYxDGCbILjR7IqWydlIXwFHfMJaboLiSksK+cx4Px8npWJGp4OecSaDQxBYjwNBMgcb9iHPpIMz6a+XaI/CD6ITvkXXZdIqVNLEcYxnc4brmbGYteIsRGGtvwvpg8RjkSCZGkuMZ0JbRqlpiXfaguS6Sx9wZePh5sOkLeFpoQpJvLByoeCsyNeQ1QvTHqjMphOwbn5j5YhciTcvtBTVQNwwylqYlA7i5V+PKsE5tZdNWKx1x2LhMKtR4V1ux6EaqZ0wWWMaHY5hPdJxZU47u1UhSFLrtYhhyKg2LfqzZI3x30gtLh4A7vhnUMG+mezbG9VaUr7Igg9gJudcS0zf0BS1KvLLw8DwaRUXq2oFIAro/nk+RjU93huvmnDZjdIFnSfXzLG36472kGUR7MQbLE589eHfw4K0Dq3oTAJtCngdpPfhylubepZy121RANXbpsquaokCcScgqvqeP5B8CLR/K9vIxKhTkCGPcjchxbg9nMktZAigdPdFZWMpsvO0AuCEGyFPESfQA1mB4kUFEXJZ4fgKfCny3d3zZjS6JpMLZPnuMVHFYf//CR4q4h91Pqs+I1yXFEhY0I5FAgVQxDlFSO525dyNPvPG5O9e6urbp94kXU1Cgcc7T18LJy3S8=
dd:
  secure: ih7BisAHlQSbcZbXd6XGlmtzKEks+HBswbcgVIx+/Apd6MS8eZMXGWJ0i3TcUkxwLwkRyPXzQJTDN6g/mH0VSKkepEVdCA4uAi6zACgK/tHDqm+hQA+FC3CxQLHwLgBaWAfelkppQty5VWuEFC4nZ8rCuoaL3CiCbX6x1yweZWpr1VvMyMTZ/oZzaopOL4UaHUOsdJvdJI+ifh+VrmqzvXnjWx8BuxyfN7+ojG5Ezm1+esHfxn6eOaKKtXz6Nq+TdZzT/MF9QaNanUTaxfNm16vFwHiVb5nEgB7ytR0In+b9P757V3ceYqVZbizRPlaK0eWQZOrbH0Kxb3+ES26+J94Wkw2OsC7u2ZZcTrZIFgLZ+GNoTyFYhCeYl3IxGE1Tj3JPn038Ykl155FUqPbnu07j3WC46qs2MFyJ7I5R/qMTflk0+WnzUhAl1aaax8v1iE98nkU77Gjo4wG/wH77UNnR/rvcgJ6QzK7AQNZWekhbtIiuwCjctLW94jYLQee1Bsn+wdDvD00XP0xNCXWX9b46Mt4L6IlCMWrntuuhCaQDtUucvXd9URdIQiSprV8sbfgpmmHDAvz4GaMFPf7xY6zJWWhtfZNX2a4UlNJI0zQ9cDH0elKK3qT9f/n3JC8no9g+1DDscXTEZVYd02F4OSKryDkrVl3PMbRMrdd9PEc=
before_install:
- openssl aes-256-cbc -K $encrypted_abf1c25cba00_key -iv $encrypted_abf1c25cba00_iv
  -in id_travis_rsa.enc -out id_travis_rsa -d
